nome = input("Digite seu nome: ")

print(f"Olá {nome}!")
print("Bem vindo ao:")
print("--- Programa da aula 1 ---")
print("Nova linha")
print("Nova linha")
print("Nova linha")
print("Nova linha")
print("Nova linha")
print("Nova linha")
print("Nova linha")
print("Nova linha")
print("Nova linha")
print("Nova linha")
print("Nova linha")
print("Nova linha")
